### ISSUE TITLE
How to set the remote agent option?

### ISSUE THREAD

**Issue by 68593018** [wwfdoink/jolokia-web#6]
I have set the option --remoteAgentUrl=http://10.42.88.21:8181/jolokia, but the result of http://localhost:8080/ is the localhost's current JVM instead of 10.42.88.21's JVM

**Comment by wwfdoink** [comment]
It was a bug and i just fixed it. Thanks for your bug report.

**Comment by 68593018** [comment]
Thanks, I just try it, it's works!

**Comment by 68593018** [comment]
I was too exciting just now, but there is still something wrong with the MBean. it only shows the directory, can't read the content of MBean

**Comment by wwfdoink** [comment]
It looks fine for me:
`java -javaagent:jolokia-jvm-1.3.7-agent.jar -jar SocketTest.jar`
`java -jar jolokia-web-0.5.3b2.jar --remoteAgentUrl=http://localhost:8778/jolokia
`
Does your agent configurered to allow HTTP GET requests only? - because this program is using POST requests except for the /jolokia/version and /jolokia/list queries. Do you get any javascript or java errors?

**Comment by 68593018** [comment]
The remote JVM(10.42.88.21) is an OSGI plantform,
`java -jar jolokia-web-master-all.jar --port=818 --remoteAgentUrl=http://10.42.88.21:8181/jolokia --remoteAgentUsername=admin --remoteAgentPassword=admin`

 The jolokia was install as a bundle, I can get the MBean information through the follow url, for example:
`http://10.42.88.21:8181/jolokia/read/java.lang:type=Memory/HeapMemoryUsage/`

but it can't read the MBean through jolokia-web and no any error display
![image 1](https://user-images.githubusercontent.com/18639309/30839113-62b7ce3e-a2a2-11e7-84af-4c728d4908c4.jpg)

**Comment by wwfdoink** [comment]
It looks like the OSGi version doesn't send the mbean **class** attribute when you call `/jolokia/list` thats why you can't see the icons next to the beans. I used that attribute to detect if a node is actually an mbean or just a folder.
```js
java.util.logging:{
    type=Logging:{
        attr: {...},
        op: {...},
        // probably this class attribute does not exists
        class: "sun.management.ManagementFactoryHelper$PlatformLoggingImpl",
        desc: "Information on the management interface of the MBean"
    }
}
```
 So it looks like i have to setup a running OSGi jolokia on my machine to double check and fix this issue.

**Comment by wwfdoink** [comment]
I just tried out the jolokia-osgi-bundle-1.3.7.jar and it works fine, can you share your /jolokia/list output?
